// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileTreeTable_Shortcuts
#define _H_FileTreeTable_Shortcuts

static const JUtf8Byte* kShortcutsMenuStr =
"* %i AddShortcut::FileTreeTable"
"|* %i RemoveShortcut::FileTreeTable"
"|* %i RemoveAllShortcuts::FileTreeTable %l"
;

enum {
	kAddShortcutCmd=1,
	kRemoveShortcutCmd,
	kRemoveAllShortcutsCmd,
};


static void ConfigureShortcutsMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#s", JString::kNoCopy));
	}
};

#endif
