// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileTreeTable_View
#define _H_FileTreeTable_View

static const JUtf8Byte* kViewMenuStr =
"* %b %i ShowFilter::FileTreeTable"
"|* %b %i ShowHidden::FileTreeTable %l"
"|* %b %i ShowUser::FileTreeTable"
"|* %b %i ShowGroup::FileTreeTable"
"|* %b %i ShowSize::FileTreeTable"
"|* %b %i ShowPermissions::FileTreeTable"
"|* %b %i ShowDate::FileTreeTable %l"
"|* %i ShowAll::FileTreeTable"
"|* %i ShowNone::FileTreeTable %l"
"|* %i Refresh::FileTreeTable"
;

enum {
	kShowFilterCmd=1,
	kShowHiddenCmd,
	kShowUserCmd,
	kShowGroupCmd,
	kShowSizeCmd,
	kShowModeCmd,
	kShowDateCmd,
	kShowAllAttrCmd,
	kHideAllAttrCmd,
	kRefreshCmd,
};

#ifndef _H_filter
#define _H_filter
#include "filter.xpm"
#endif
#ifndef _H_hidden
#define _H_hidden
#include "hidden.xpm"
#endif
#ifndef _H_user
#define _H_user
#include "user.xpm"
#endif
#ifndef _H_group
#define _H_group
#include "group.xpm"
#endif
#ifndef _H_size
#define _H_size
#include "size.xpm"
#endif
#ifndef _H_mode
#define _H_mode
#include "mode.xpm"
#endif
#ifndef _H_month
#define _H_month
#include "month.xpm"
#endif

static void ConfigureViewMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#v", JString::kNoCopy));
	}
	menu->SetItemImage(kShowFilterCmd + offset, filter);
	menu->SetItemImage(kShowHiddenCmd + offset, hidden);
	menu->SetItemImage(kShowUserCmd + offset, user);
	menu->SetItemImage(kShowGroupCmd + offset, group);
	menu->SetItemImage(kShowSizeCmd + offset, size);
	menu->SetItemImage(kShowModeCmd + offset, mode);
	menu->SetItemImage(kShowDateCmd + offset, month);
};

#endif
