// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileTreeTable_View_enum
#define _H_FileTreeTable_View_enum

enum {
	kShowFilterCmd=1,
	kShowHiddenCmd,
	kShowUserCmd,
	kShowGroupCmd,
	kShowSizeCmd,
	kShowModeCmd,
	kShowDateCmd,
	kShowAllAttrCmd,
	kHideAllAttrCmd,
	kRefreshCmd,
};

#endif
