// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileTreeTable_Edit_enum
#define _H_FileTreeTable_Edit_enum

enum {
	__SGCopyWithPath=1,
};

#endif
