// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileTreeTable_Git_enum
#define _H_FileTreeTable_Git_enum

enum {
	kGitSwitchBranchItemIndex=1,
	kGitStatusCmd,
	kGitHistoryCmd,
	kGitCommitAllCmd,
	kGitRevertAllCmd,
	kGitStashChangesCmd,
	kGitStashPopItemIndex,
	kGitStashApplyItemIndex,
	kGitStashDropItemIndex,
	kGitPullItemIndex,
	kGitPushItemIndex,
	kGitMergeFromBranchItemIndex,
	kGitFetchBranchItemIndex,
	kGitCreateBranchCmd,
	kGitRemoveBranchItemIndex,
	kGitAddRemoteCmd,
	kGitRemoveRemoteItemIndex,
	kGitPruneRemoteItemIndex,
};

#endif
