// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileTreeTable_Context
#define _H_FileTreeTable_Context

static const JUtf8Byte* kContextMenuStr =
"* %i __Duplicate::FileTreeTable"
"|* %i __MakeAlias::FileTreeTable"
"|* %i __FindOriginal::FileTreeTable %l"
"|* %i __OpenThisAndCloseWindow::FileTreeTable"
"|* %i __OpenThisAndIconifyWindow::FileTreeTable %l"
"|* %i __RunCommandOnSelection::FileTreeTable %l"
"|* %i __ConvertToFile::FileTreeTable"
"|* %i __ConvertToProgram::FileTreeTable"
;

enum {
	kDuplicateCtxCmd=1,
	kMakeAliasCtxCmd,
	kFindOriginalCtxCmd,
	kOpenCloseCtxCmd,
	OpenIconifyCtxCmd,
	kRunOnSelCtxCmd,
	kConvertToFileCtxCmd,
	kConvertToProgramCtxCmd,
};

#ifndef _H_jx_af_image_jx_jx_library_file_small
#define _H_jx_af_image_jx_jx_library_file_small
#include <jx-af/image/jx/jx_library_file_small.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_plain_file_small
#define _H_jx_af_image_jx_jx_plain_file_small
#include <jx-af/image/jx/jx_plain_file_small.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_executable_small
#define _H_jx_af_image_jx_jx_executable_small
#include <jx-af/image/jx/jx_executable_small.xpm>
#endif

static void ConfigureContextMenu(JXTextMenu* menu, const int offset = 0) {
	menu->SetItemImage(kDuplicateCtxCmd + offset, jx_library_file_small);
	menu->SetItemImage(kConvertToFileCtxCmd + offset, jx_plain_file_small);
	menu->SetItemImage(kConvertToProgramCtxCmd + offset, jx_executable_small);
};

#endif
