// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileTreeTable_File_enum
#define _H_FileTreeTable_File_enum

enum {
	kNewDirCmd=1,
	kNewTextFileCmd,
	kOpenCmd,
	kOpenCloseCmd,
	kOpenIconifyCmd,
	kAltOpenCmd,
	kRunOnSelCmd,
	kFindCmd,
	kOpenRecentItemIndex,
	kRenameCmd,
	kConvertToFileCmd,
	kConvertToProgramCmd,
	kDuplicateCmd,
	kMakeAliasCmd,
	kFindOriginalCmd,
	kToggleMountCmd,
	kEraseDiskCmd,
	kHomeWindowCmd,
	kViewManCmd,
	kOpenTermCmd,
	kRunCmdCmd,
	kCloseCmd,
	kQuitCmd,
};

#endif
