// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileTreeTable_Shortcuts_enum
#define _H_FileTreeTable_Shortcuts_enum

enum {
	kAddShortcutCmd=1,
	kRemoveShortcutCmd,
	kRemoveAllShortcutsCmd,
};

#endif
