// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileTreeTable_Git
#define _H_FileTreeTable_Git

static const JUtf8Byte* kGitMenuStr =
"* %i __Branch::FileTreeTable %l"
"|* %i GitStatus::FileTreeTable"
"|* %i GitHistory::FileTreeTable"
"|* %i GitCommitAll::FileTreeTable"
"|* %i GitRevertAll::FileTreeTable"
"|* %i GitStashChanges::FileTreeTable"
"|* %i __Pop::FileTreeTable"
"|* %i __Apply::FileTreeTable"
"|* %i __Drop::FileTreeTable %l"
"|* %i __PullFromRemote::FileTreeTable"
"|* %i __PushCurrentBranchToRemote::FileTreeTable %l"
"|* %i __MergeFromBranch::FileTreeTable %l"
"|* %i __FetchRemoteBranch::FileTreeTable"
"|* %i GitCreateBranch::FileTreeTable"
"|* %i __RemoveLocalBranch::FileTreeTable %l"
"|* %i GitAddRemote::FileTreeTable"
"|* %i __RemoveRemote::FileTreeTable"
"|* %i GitPruneRemote::FileTreeTable"
;

enum {
	kGitSwitchBranchItemIndex=1,
	kGitStatusCmd,
	kGitHistoryCmd,
	kGitCommitAllCmd,
	kGitRevertAllCmd,
	kGitStashChangesCmd,
	kGitStashPopItemIndex,
	kGitStashApplyItemIndex,
	kGitStashDropItemIndex,
	kGitPullItemIndex,
	kGitPushItemIndex,
	kGitMergeFromBranchItemIndex,
	kGitFetchBranchItemIndex,
	kGitCreateBranchCmd,
	kGitRemoveBranchItemIndex,
	kGitAddRemoteCmd,
	kGitRemoveRemoteItemIndex,
	kGitPruneRemoteItemIndex,
};

#ifndef _H_git_status
#define _H_git_status
#include "git_status.xpm"
#endif
#ifndef _H_git_history
#define _H_git_history
#include "git_history.xpm"
#endif
#ifndef _H_git_commit_all
#define _H_git_commit_all
#include "git_commit_all.xpm"
#endif
#ifndef _H_git_revert_all
#define _H_git_revert_all
#include "git_revert_all.xpm"
#endif

static void ConfigureGitMenu(JXTextMenu* menu, const int offset = 0) {
	if (menu->IsEmpty() && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#g", JString::kNoCopy));
	}
	menu->SetItemImage(kGitStatusCmd + offset, git_status);
	menu->SetItemImage(kGitHistoryCmd + offset, git_history);
	menu->SetItemImage(kGitCommitAllCmd + offset, git_commit_all);
	menu->SetItemImage(kGitRevertAllCmd + offset, git_revert_all);
};

#endif
