// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileTreeTable_Edit
#define _H_FileTreeTable_Edit

static const JUtf8Byte* kEditMenuStr =
"* %i CopyWithPath::FileTreeTable"
;

#include "FileTreeTable-Edit-enum.h"


static void ConfigureEditMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
