/******************************************************************************
 MDIServer.h

	Interface for the MDIServer class

	Copyright (C) 1997 by Glenn W. Bach.

	Base code generated by Codemill v0.1.0

 *****************************************************************************/

#ifndef _H_MDIServer
#define _H_MDIServer

#include <jx-af/jx/JXMDIServer.h>

class MDIServer : public JXMDIServer
{
public:

	MDIServer();

	virtual	~MDIServer();

	static void	PrintCommandLineHelp();

protected:

	void	HandleMDIRequest(const JString& dir,
									 const JPtrArray<JString>& argList) override;

private:

	void	OpenFiles();
};

#endif
