// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TreeDir_Help_enum
#define _H_TreeDir_Help_enum

enum {
	kAboutCmd=1,
	kTOCCmd,
	kOverviewCmd,
	kChangesCmd,
	kCreditsCmd,
};

#endif
