// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TreeDir_Preferences
#define _H_TreeDir_Preferences

static const JUtf8Byte* kPreferencesMenuStr =
"* %i __Preferences::TreeDir"
"|* %i __FileBindings::TreeDir"
"|* %i __EditToolBar::TreeDir"
"|* %i __MacWinXEmulation::TreeDir %l"
"|* %i __SaveWindowSetupAsDefault::TreeDir"
;

#include "TreeDir-Preferences-enum.h"


static void ConfigurePreferencesMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#p");
	}
};

#endif
