#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1

BIN=$PRE/usr/bin
DOC=$PRE/usr/share/doc/systemg
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

if [[ ! -z $PRE ]]; then
	mkdir -p $BIN $APP $ICON;
fi

# systemg

install -m755 systemg $BIN

mkdir -p $DOC
cp README.md COPYING menu_strings $DOC

cp desktop/systemg.desktop        $APP/
cp desktop/systemg_choose.desktop $APP/
cp desktop/systemg.xpm            $ICON/
