#!/bin/bash

PRE=$1;
if [[ -z $PRE ]]; then
	PRE=/usr/local;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/systemg;
APP=$PRE/share/applications;
ICON=$PRE/share/pixmaps;

rm -f  $BIN/systemg;
rm -rf $DOC;
rm -f  `find $APP -name 'systemg*.desktop'`;
rm -f  `find $ICON -name 'systemg*.png'`;
