#!/bin/bash

PRE=$1;

BIN=$PRE/usr/bin;
DOC=$PRE/usr/share/doc/systemg;
APP=$PRE/usr/share/applications;
ICON=$PRE/usr/share/pixmaps;

rm -f  $BIN/systemg;
rm -rf $DOC;
rm -f  `find $APP -name 'systemg*.desktop'`;
rm -f  `find $ICON -name 'systemg*.png'`;
